# Generated by Django 3.2.3 on 2021-10-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_blog_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='authorname',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='register',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='register',
            name='title',
        ),
        migrations.AddField(
            model_name='register',
            name='Username',
            field=models.CharField(default='string', max_length=30),
        ),
        migrations.AddField(
            model_name='register',
            name='password',
            field=models.CharField(default='pass', max_length=30),
        ),
        migrations.AddField(
            model_name='register',
            name='phone',
            field=models.CharField(default='0000', max_length=20),
        ),
    ]
