# Generated by Django 3.2.3 on 2021-10-01 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211001_1602'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Registers',
        ),
    ]
