# Generated by Django 3.2.3 on 2021-10-10 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_register_registers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registers',
            new_name='Register',
        ),
    ]
